title: Dominic Castaneda # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! My name is Dominic and I'm a software engineer from Southern California.  
  I'm experienced in all aspects of the software development lifecycle and project management, 
  from planning, designing, building testing, and deployment. I have become a creative problem 
  solver with a passion for developing innovative solutions for complex problems.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/dominic-castaneda/">View My LinkedIn Profile</a>
  <a href="https://github.com/DomCastaneda">View My GitHub Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-KYDKGF60PC # your Google Analytics tracking ID here
