title: Dominic Castaneda
logo: "/images/logo.png?raw=true"
description: >
  Hello! My name is Dominic and I'm a software engineer from Southern California.  
  I'm experienced in all aspects of the software development lifecycle 
  including: planning, designing, building testing, and deployment. Something that I love about software 
  development is the opportunity to work on a team and connect with others. I’m eager to meet 
  and learn from other software engineers, so feel free to connect on LinkedIn!
  <br></br>
  <a href="/images/Dominic-Castaneda-Resume.pdf" download="Dominic-Castaneda-Resume">My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/dominic-castaneda/"><img src="/images/linkedin.png?raw=true"></a>
  <a href="https://github.com/DomCastaneda"><img src="/images/github.png?raw=true"></a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-KYDKGF60PC # Google Analytics tracking ID here
