title: Dominic Castaneda # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! My name is Dominic and I'm a software engineer from Southern California.  
  I'm experienced in all aspects of the software development lifecycle and project management, 
  from planning, designing, building testing, and deployment. I have become a creative problem 
  solver with a passion for developing innovative solutions for complex problems.
  <br><br>
  Something that I love about software development is the opportunity to work on a team and connect with others.
  In my free time you might find me: hiking, running, boxing, cooking, watching anime, fishing, reading A Song of Ice and Fire, 
  or rooting for my favorite sports teams. I’m eager to meet and learn from other software engineers, so feel free to connect on LinkedIn! 
  <br><br>
  <a href="https://www.linkedin.com/in/dominic-castaneda/">View My LinkedIn Profile</a>
  <a href="https://github.com/DomCastaneda">View My GitHub Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
